In [ ]:
import numpy as np 

In [ ]:
""" PUZZLE CLASS """
""" 22p22c0398 Phonratichai waitrotchanaphuttha

"""
class Puzzle:
    goal_state=[1,2,3,8,0,4,7,6,5] #ตั้งค่า goal_state
    heuristic=None
    evaluation_function=None
    needs_hueristic=True
    def __init__(self,state,parent,action,path_cost,needs_hueristic=True,display=True):
        self.parent=parent
        self.state=state
        self.action=action
        self.needs_hueristic
        self.display = display
        if parent:
            self.path_cost = parent.path_cost + path_cost
        else:
            self.path_cost = path_cost
        if needs_hueristic:
            self.needs_hueristic=True
            self.gen_heuristic()
            self.evaluation_function=self.heuristic+self.path_cost #f_score = h_score + g_core

    def gen_heuristic(self):
        ''' คำนวนระยะห่างระหว่าง state ปัจจุบัน กับ goal_state '''
        self.heuristic=0
        for num in range(1,9):
            distance=abs(self.state.index(num) - self.goal_state.index(num))
            i=int(distance/3)
            j=int(distance%3)
            self.heuristic=self.heuristic+i+j
    
    def display_board(self):
      if self.display:
        print("= > show state <=")
        return print(np.array(self.state).reshape(3,3))

    def is_win(self):
        if self.state == self.goal_state:
            print("finish goal test")
            print(np.array(self.state).reshape(3,3))
            return True
        return False

    @staticmethod
    def check_action_can_move(i,j): 
        actions = ['U', 'D', 'L', 'R']
        if i == 0:  
            actions.remove('U')
        elif i == 2:  
            actions.remove('D')
        if j == 0:
            actions.remove('L')
        elif j == 2:
            actions.remove('R')
        return actions

    def gen_child(self):
        children=[]
        x = self.state.index(0)
        i = int(x / 3)
        j = int(x % 3)
        actions=self.check_action_can_move(i,j)

        for action in actions:
            new_state = self.state.copy()
            if action is 'U':
                new_state[x], new_state[x-3] = new_state[x-3], new_state[x]
            elif action is 'D':
                new_state[x], new_state[x+3] = new_state[x+3], new_state[x]
            elif action is 'L':
                new_state[x], new_state[x-1] = new_state[x-1], new_state[x]
            elif action is 'R':
                new_state[x], new_state[x+1] = new_state[x+1], new_state[x]
            children.append(Puzzle(new_state,self,action,1,self.needs_hueristic,self.display))
        self.display_board()
        return children

    def find_solution(self):
        solution = []
        solution.append(self.action)
        path = self
        while path.parent != None:
            path = path.parent
            solution.append(path.action)
        solution = solution[:-1]
        solution.reverse()
        return solution

In [ ]:
from time import time 
from queue import PriorityQueue

''' a * imprement  '''
def a_star_search(puzzle):
    t0 = time()
    count=0
    explored=[]
    q = PriorityQueue()
    q.put((puzzle.evaluation_function,count,puzzle))

    while not q.empty():
        node=q.get()
        node=node[2] # เรียก Class Puzzle ที่เก็บไว้ขึ้นมา ทำให้สามารถ
        explored.append(node.state) #เก็บ state ปัจจุบันไว้ใน list
        if node.is_win(): # call check win
            t1 = time() - t0
            print('finish time:', t1)
            return node.find_solution()

        children=node.gen_child()
        for child in children:
            if child.state not in explored:
                count += 1
                q.put((child.evaluation_function,count,child))
    return

In [ ]:
puzzle_problem = [1, 3, 4,
                  8, 6, 2,
                  7, 0, 5]

In [ ]:
puzzle = Puzzle(puzzle_problem,None,None,0,False,True)
astar = a_star_search(puzzle)
print('A* move:',astar)
print('count move:', len(astar)) #ไม่รวม init state

= > show state <=
[[1 3 4]
 [8 6 2]
 [7 0 5]]
= > show state <=
[[1 3 4]
 [8 0 2]
 [7 6 5]]
= > show state <=
[[1 3 4]
 [8 2 0]
 [7 6 5]]
= > show state <=
[[1 3 0]
 [8 2 4]
 [7 6 5]]
= > show state <=
[[1 0 3]
 [8 2 4]
 [7 6 5]]
finish goal test
[[1 2 3]
 [8 0 4]
 [7 6 5]]
finish time: 0.002921581268310547
A* move: ['U', 'R', 'U', 'L', 'D']
count move: 5
